# Ime skripta
name: Sync to Sara Repo

# Kada da se pokrene? - Svaki put kad se desi PUSH u 'main' granu
on:
  push:
    branches: [ "main" ]

# Poslovi koje treba obaviti
jobs:
  mirror-sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Preuzmi kod sa trenutnog repa (tpktehnoco)
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Preuzmi celu istoriju

      # 2. Poveži se na drugi rep (sara) i pošalji kod
      - name: Mirror to Sara Account
        run: |
          git config --global user.name "tpktehnoco"
          git config --global user.email "tpktehnoco@users.noreply.github.com"
          git remote add mirror https://x-access-token:${{ secrets.SARA_TOKEN }}@github.com/paintedbysaraa/make-up.git
          git push mirror main --force
